# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               remote-lab.net
tagline:             'learn by doing'
description:         'A place to learn system and network administration'
url:                 https://remote-lab.net
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Marius Cornea
  url:               https://www.facebook.com/marius.catalin.31542
  email:             marius@remote-lab.net

# Custom vars
version:             1.0.0

# Gems
gems:
  - jekyll-gist
  - jekyll-paginate
